mapping_long = {
    "RESIDENT_NO_RESIDENT": "Resident / non-resident",
    "A6": "6. Income from selling goods",
    "A7": "7. Income from selling production",
    "A8": "8. Income from performing work",
    "A9": "9. Income from providing services",
    "A9_1": "1) Income from freight services by entrepreneurs",
    "A10": "10. Income from mediation agreements",
    "A11": "11. Income from selling fixed assets",
    "A12": "12. Income from selling intangible assets",
    "A13": "13. Income from selling other assets",
    "A14": "14. Income from dividends",
    "A15": "15. Interest income from loans",
    "A16": "16. Interest income from provided loans",
    "A17": "17. Interest income from financial lease",
    "A18": "18. Income from rent or operating lease fees",
    "A19": "19. Income from royalties",
    "A20": "20. Income from free cash received",
    "A21": "21. Income from land received for free",
    "A22": "22. Income from other assets received free of charge",
    "A23": "23. Income from assets transferred by court decisions",
    "A24": "24. Income from forfeited assets recognized by law",
    "A25": "25. Income from surplus inventory found",
    "A26": "26. Income from discounted or forgiven obligations",
    "A27": "27. Income from discounts or pardoned obligations",
    "A28": "28. Income from damages or losses",
    "A29": "29. Income from penalties, fines, and sanctions",
    "A30": "30. Income from adjustments to prior period deductions",
    "A31": "31. Income from written-off payables",
    "A32": "32. Income from repayment of written-off receivables",
    "A33": "33. Income from adjusted reserves for receivables",
    "A34": "34. Income from recovering bad assets or securities",
    "A35": "35. Income from reducing unneeded reserves for assets",
    "A36": "36. Income from insurance technical reserves",
    "A37": "37. Income from reinsurance commissions",
    "A38": "38. Income from derivative financial instruments",
    "A39": "39. Income from VAT adjustments",
    "A40": "40. Other income",
    "A41": "41. Gross income (sum of items 6-40)",
    "A41A": "1) Income from patent-taxable activities",
    "A41B": "2) Income from joint activities",
    "A41C": "3) Income from production in border zones",
    "A42": "42. Initial cost of supplied goods",
    "A43": "43. Costs related to producing goods",
    "A44": "44. Costs related to performing work",
    "A45": "45. Costs related to providing services",
    "A46": "46. Costs related to mediation agreements",
    "A47": "47. Book value of sold fixed assets",
    "A48": "48. Book value of sold intangible assets",
    "A49": "49. Book value of other sold assets",
    "A50": "50. Administrative costs, including:",
    "A50_1": "1) Business trips outside Armenia",
    "A50_2": "2) Business trips within Armenia",
    "A50_3": "3) Representative expenses",
    "A50_4": "4) Management services expenses",
    "A50_5": "5) Consulting services expenses",
    "A50_6": "6) Information services expenses",
    "A51": "51. Sales costs, including:",
    "A51_1": "1) Advertising expenses",
    "A51_2": "2) Marketing costs",
    "A52": "52. Non-production expenses",
    "A53": "53. Financial expenses, including:",
    "A53_1": "1) Interest on loans from banks",
    "A53_2": "2) Interest on loans from non-bank entities",
    "A54": "54. Costs for social or cultural events",
    "A55": "55. Insurance and reinsurance costs",
    "A56": "56. Rental fees or service costs",
    "A57": "57. Costs for damage compensation",
    "A58": "58. Costs for penalties and sanctions",
    "A59": "59. Non-refundable taxes, duties, or fees",
    "A60": "60. Costs deducted from VAT amounts",
    "A61": "61. Other costs",
    "A62": "62. Total costs (items 42-61)",
    "A63": "63. Losses from natural causes",
    "A64": "64. Losses from quality issues",
    "A65": "65. Random losses",
    "A66": "66. Other losses",
    "A67": "67. Total losses (items 63-66)",
    "A68": "68. Deductions from invalid prior transactions",
    "A69": "69. Deductions for bad debt allowances",
    "A70": "70. Amounts exceeding bad debt reserves",
    "A71": "71. Repayment of previously written-off debts",
    "A72": "72. Reserves for possible asset or securities losses",
    "A73": "73. Insurance or reinsurance payments",
    "A74": "74. Costs for insurance technical reserves",
    "A75": "75. Losses from counterfeit banknotes or payments",
    "A76": "76. Tax losses from the prior 5 years",
    "A77": "77. Value of assets or services provided to public institutions or non-profits",
    "A78": "78. Additional deduction for employing disabled workers",
    "A79": "79. Payments to registered financial instruments",
    "A80": "80. Dividends paid to resident taxpayers",
    "A81": "81. Retirement fees for entrepreneurs or notaries",
    "A82": "82. Other deductions",
    "A83": "83. Total reductions (items 68-82)",
    "A84": "84. Total reductions (items 62 + 67 + 83)",
    "A84_1": "1) Reductions from patent-taxable activities",
    "A84_2": "2) Reductions from joint activities",
    "A84_3": "3) Reductions for production in border zones",
    "A85": "85. Taxable profit or tax loss after reductions",
    "A86": "86. Tax benefits reducing taxable profit",
    "A87": "87. Taxable profit after applying tax benefits",
    "A88": "88. Calculated profit tax for the year",
    "A89": "89. Government-approved profit tax benefits",
    "A90": "90. Profit tax reductions for specific citizens or services",
    "A91": "91. Total profit tax reductions (items 89 + 90)",
    "A92": "92. Profit tax after reductions",
    "A93": "93. Undeducted foreign profit tax from prior years",
    "A94": "94. Foreign profit tax for the current year",
    "A95": "95. Deducted foreign profit tax for the current year",
    "A96": "96. Undeducted foreign profit tax carried forward",
    "A97": "97. Profit tax withheld for permanent establishments",
    "A98": "98. Final profit tax after deductions",
    "A99": "99. Profit tax on income not from permanent establishments",
    "A100": "100. Total profit tax (items 98 + 99)",
    "A101": "101. Total prepayments toward profit tax",
    "A102": "102. Profit tax after deducting prepayments",
    "A103": "103. Minimum profit tax not yet deducted",
    "A104": "104. Final profit tax payable",
    "A105": "105. Minimum profit tax carried forward",
    "A106": "106. Profit tax eligible for reimbursement",
    "A107": "107. Profit tax for entrepreneurs and notaries",
    "v7a": "7. MAINTENANCE OF 20% OF [a] VAT- the taxable base",
    "v7b": "7. 20% VAT rate taxable transactions [b] .VAT Credit",
    "v8a1": "8. Reduction of transactions with adjustable tax accounts [a] VAT- the taxable base",
    "v8a2": "8. Determination of transactions with adjustment tax accounts [b] VAT Credit",
    "v8b1": "8. Adjustment Tax Account Deals: 2) additions [a] VAT- the taxable base",
    "v8b2": "8. Adjustment Tax Account Deals: 2) additions [b] VAT Credit",
    "v9a": "9. 16.67% Taxable Rate [a] VAT- the taxable base",
    "v9b": "9. 16.67% Taxable Rate [b] VAT Credit",
    "v10": "10. Other tax liability on VAT",
    "v111": "11. Reduction of transactions with adjustable tax accounts written from the supplier",
    "v112": "11. Additions of transactions with adjustable tax accounts written from the supplier",
    "v12": "12. Transactions taxed at 0 VAT rate, including: 1) Article 2) part 3) point of the Tax Code",
    "v13": "13. Article 2 of the Tax Code of VAT, including 1)",
    "v14": "14. The clause was declared invalid on 2020. from January 1",
    "v15a": "15. Adjustment of calculated VAT tax liabilities (VAT credit) [A]: Addition",
    "v15b": "15. Adjustment of calculated VAT tax liabilities (VAT credit) [B]: Reduction",
    "v16a": "16. Total VAT credit [A]. Taxation base",
    "v16b": "16. Total VAT credit [B]. VAT credit",
    "v17a": "17. Value of goods imported into RA territory [A]",
    "v17b": "17. VAT debit of goods imported to the RA territory [B]",
    "v18a": "18. Cost of goods and services purchased in the territory of the Republic of Armenia [A]",
    "v18b": "18. VAT debit of goods and services purchased in the RA territory [B]",
    "v19a1": "19. Deduction of transactions with adjusting tax accounts related to acquisitions 1) [A]. Value",
    "v19b1": "19. Deduction of transactions with adjusting tax accounts related to acquisitions [B]: VAT debit",
    "v19a2": "19. Addition of transactions2) with adjusting tax accounts related to acquisitions [A]. Value",
    "v19b2": "19. Addition of transactions2) with adjusting tax accounts related to acquisitions [B]: VAT debit",
    "v20a": "20. Total adjustment of the amount of VAT subject to settlement (reduction) [A]: Addition",
    "v20b": "20. Total adjustment of the amount of VAT subject to settlement (reduction) [B]: Reduction",
    "v21a": "21. Total VAT debit ([A]: Positive)",
    "v21b": "21. Total VAT debit ([B]: Negative)",
    "v22a": "22. Imported goods VAT (Tax base) [A]",
    "v22b": "22. Imported goods VAT (Calculated VAT amount) [B]",
    "v23a": "23. VAT calculated for the reporting period [A]: Amount of VAT payable to the state budget",
    "v23b": "23. VAT calculated for the reporting period [B]: Amount of VAT to be reimbursed from the state budget",
    "v24": "24. Excise tax taxation base and calculated excise tax amount",
    "v25": "25. Excise tax amount (reduction) of goods subject to excise tax",
    "v26": "26. Excise tax amount of goods subject to excise tax (addition)",
    "v27": "27. Calculated excise tax amount (excise tax credit)",
    "v281": "28.1. Excise tax amount for transactions with adjusting tax accounts: reduction",
    "v282": "28.2. Excise tax amount for transactions with adjusting tax accounts: addition",
    "v29": "29. Taxation base of expropriated goods exempted from excise tax",
    "v30": "30. Amount of excise tax for raw materials imported into the RA territory",
    "v31": "31. Amount of excise tax for raw materials purchased in the RA territory",
    "v32a": "32. Total amount of excise tax adjustment (Addition) [A]",
    "v32b": "32. Total amount of excise tax adjustment (Reduction) [B]",
    "v33a": "33. Total excise tax debit in the reporting period [A]: Positive",
    "v33b": "33. Total excise tax debit in the reporting period [B]: Negative",
    "v34a": "34. Excise tax payable to the state budget [A]",
    "v34b": "34. Excise tax to be reimbursed from the state budget [B]",
    "v7a_mean": "Mean 20% VAT rate taxable base per month",
    "v7b_mean": "Mean 20% VAT rate taxable transactions (VAT Credit) per month",
    "v8a1_mean": "Mean reduction of transactions with adjustable tax accounts (VAT-taxable base) per month",
    "v8a2_mean": "Mean determination of transactions with adjustable tax accounts (VAT Credit) per month",
    "v8b1_mean": "Mean adjustment tax account deals additions (VAT-taxable base) per month",
    "v8b2_mean": "Mean adjustment tax account deals additions (VAT Credit) per month",
    "v9a_mean": "Mean 16.67% taxable rate (VAT-taxable base) per month",
    "v9b_mean": "Mean 16.67% taxable rate (VAT Credit) per month",
    "v10_mean": "Mean other tax liability on VAT per month",
    "v111_mean": "Mean reduction of transactions with adjustable tax accounts per month",
    "v112_mean": "Mean additions of transactions with adjustable tax accounts per month",
    "v12_mean": "Mean transactions taxed at 0 VAT rate per month",
    "v13_mean": "Mean Article 2 VAT transactions per month",
    "v14_mean": "Mean invalid clause transactions per month",
    "v15a_mean": "Mean adjustment of calculated VAT tax liabilities (Addition) per month",
    "v15b_mean": "Mean adjustment of calculated VAT tax liabilities (Reduction) per month",
    "v16a_mean": "Mean total VAT credit (Taxation base) per month",
    "v16b_mean": "Mean VAT credit per month",
    "v17a_mean": "Mean value of goods imported into RA territory per month",
    "v17b_mean": "Mean VAT debit of goods imported into RA territory per month",
    "v18a_mean": "Mean cost of goods and services purchased in RA territory per month",
    "v18b_mean": "Mean VAT debit of goods and services purchased in RA territory per month",
    "v19a1_mean": "Mean deduction of transactions with adjusting tax accounts (Value) per month",
    "v19b1_mean": "Mean deduction of transactions with adjusting tax accounts (VAT debit) per month",
    "v19a2_mean": "Mean addition of transactions with adjusting tax accounts (Value) per month",
    "v19b2_mean": "Mean addition of transactions with adjusting tax accounts (VAT debit) per month",
    "v20a_mean": "Mean total VAT adjustment (Addition) per month",
    "v20b_mean": "Mean total VAT adjustment (Reduction) per month",
    "v21a_mean": "Mean total VAT debit (Positive) per month",
    "v21b_mean": "Mean total VAT debit (Negative) per month",
    "v22a_mean": "Mean imported goods VAT (Tax base) per month",
    "v22b_mean": "Mean imported goods VAT (Calculated VAT amount) per month",
    "v23a_mean": "Mean VAT payable to the state budget per month",
    "v23b_mean": "Mean VAT reimbursed from the state budget per month",
    "v24_mean": "Mean excise tax base and calculated amount per month",
    "v25_mean": "Mean excise tax amount (reduction) per month",
    "v26_mean": "Mean excise tax amount (addition) per month",
    "v27_mean": "Mean excise tax credit per month",
    "v281_mean": "Mean excise tax amount for adjusting accounts (reduction) per month",
    "v282_mean": "Mean excise tax amount for adjusting accounts (addition) per month",
    "v29_mean": "Mean taxation base of expropriated goods per month",
    "v30_mean": "Mean excise tax for raw materials imported per month",
    "v31_mean": "Mean excise tax for raw materials purchased per month",
    "v32a_mean": "Mean excise tax adjustment (Addition) per month",
    "v32b_mean": "Mean excise tax adjustment (Reduction) per month",
    "v33a_mean": "Mean total excise tax debit (Positive) per month",
    "v33b_mean": "Mean total excise tax debit (Negative) per month",
    "v34a_mean": "Mean excise tax payable to the state budget per month",
    "v34b_mean": "Mean excise tax reimbursed from the state budget per month",
    "A9_ALL": "Sum of income from the provision of services (A9) and income from freight of individual entrepreneurs (A9_1)",
    "ALL_105": "Sum of income from alienation of fixed assets (A11), intangible assets (A12), and other assets (A13)",
    "ALL_106": "Sum of percentage income from loans (A15), provision of loans (A16), and financial lease (A17)",
    "ALL_113": "Sum of income from free cash (A20), free-obtained lands (A21), free-obtained assets (A22), and assets transferred by court decisions (A23)",
    "ALL_117": "Sum of income from surplus property found during inventory (A24) and from forgiven or discounted obligations (A25)",
    "ALL_203": "Sum of costs directly related to the provision of services (A45) and mediation contracts (A46)",
    "ALL_204": "Sum of carrying amount of alienated fixed assets (A47), intangible assets (A48), and other alienated assets (A49)",
    "profitability": "Profitability ratio calculated as income minus costs (percentage)",
    "admin_ratio": "Ratio of administrative costs (A50) to total reductions or income, measuring operational efficiency",
    "A50_lagged": "Lagged version of A50: Administrative costs, including business trips, consulting, and management expenses",
    "A85_lagged": "Lagged version of A85: Taxable profit or tax loss",
    "A84_lagged": "Lagged version of A84: Total reductions, including reductions from costs and losses",
    "A41_lagged": "Lagged version of A41: Gross income (total income from all revenue streams)",
    "has_new_financials": "Has Shahuthark data",
    "has_financial": "Has VAT data",
    "var1": "Proportion of 20% VAT taxable base (7a) relative to total VAT-related sales (7a + 9a + 12 + 13)",
    "var1_std": "Variability in the proportion of 20% VAT taxable base relative to total VAT-related sales",
    "var2": "Proportion of 16.67% VAT taxable base (9a) relative to total VAT-related sales (7a + 9a + 12 + 13)",
    "var2_std": "Variability in the proportion of 16.67% VAT taxable base relative to total VAT-related sales",
    "var3": "Proportion of 0% VAT rate transactions (12) relative to total VAT-related sales (7a + 9a + 12 + 13)",
    "var3_std": "Variability in the proportion of 0% VAT rate transactions relative to total VAT-related sales",
    "var4": "Proportion of VAT transactions under Article 2 (13) relative to total VAT-related sales (7a + 9a + 12 + 13)",
    "var4_std": "Variability in the proportion of Article 2 VAT transactions relative to total VAT-related sales",
    "var5": "Ratio of zero-rated VAT transactions (12 + 13) to total VAT credit (16a)",
    "var5_std": "Variability in the ratio of zero-rated VAT transactions to total VAT credit",
    "var6": "Ratio of total VAT credit (16b) to the adjusted 20% VAT taxable base [(8a.1 + 9a - 9b)*0.2]",
    "var6_std": "Variability in the ratio of VAT credit to the adjusted 20% VAT base",
    "var7": "Ratio of total VAT credit (16a) to the total value of acquisitions (17a + 18a), showing how sales align with purchases",
    "var7_std": "Variability in the ratio of VAT credit to total acquisitions",
    "var8": "Share of VAT debit adjustments (21a - 21b) relative to total acquisitions (17a + 18a)",
    "var8_std": "Variability in the share of VAT debit adjustments relative to acquisitions",
    "var9": "Proportion of transactions with VAT credit adjustments (8a.1) relative to total VAT credit (16a)",
    "var9_std": "Variability in the proportion of VAT credit adjustments relative to total VAT credit",
    "var10": "Proportion of reductions in VAT credit adjustments (11.1) relative to total VAT credit (16b)",
    "var10_std": "Variability in the proportion of reductions in VAT credit adjustments relative to total VAT credit",
    "n_MONTH_filed": "Number of months with filed financial records (count of FILE_PERIOD)",
    "TOTAL": "Total value of 20% taxable base (v7a), 16.67% taxable base (v9a), 0% taxed (v12), and Article 2 VAT (v13)",
    "TOTAL_CHANGE": "Change in TOTAL value compared to the previous year (same TIN)",
    "7a_CHANGE": "Change in the 20% VAT taxable base (v7a) compared to the previous year (same TIN)",
    "var1_CHANGE": "Change in the share of 20% VAT taxable base (var1) compared to previous year (same TIN)",
    "var2_CHANGE": "Change in the share of 16.67% VAT taxable base (var2) compared to previous year (same TIN)",
    "var3_CHANGE": "Change in the share of 0% VAT taxable transactions (var3) compared to previous year",
    "var4_CHANGE": "Change in the share of Article 2 VAT transactions (var4) compared to previous year",
    "var5_CHANGE": "Change in ratio of zero-rate VAT (v12+v13) to total VAT credit (v16a) compared to previous year",
    "var6_CHANGE": "Change in ratio of total VAT credit (v16b) to adjusted 20% VAT base compared to previous year",
    "var7_CHANGE": "Change in ratio of total VAT credit (v16a) to total acquisitions (v17a+v18a) compared to previous year",
    "var8_CHANGE": "Change in share of VAT debit adjustment (v21a - v21b) relative to total acquisitions (v17a+v18a) compared to previous year",
    "var9_CHANGE": "Change in ratio of VAT credit adjustments (v8a.1) to total VAT credit (v16a) compared to previous year",
    "AVG_N_EMPLOYEES": "Average number of employees per period",
    "EMPLOYEE_CHANGE": "Change in average employees from previous period",
    "PERCENT_CHANGE": "Percentage change in average employees",
    "ROLLING_MEAN_EMP": "4-period rolling average of employees",
    "ROLLING_STD_EMP": "4-period rolling std dev of employees",
    "MOMENTUM": "Change in employee count change",
    "month_1": "Employees in January",
    "month_2": "Employees in February",
    "month_3": "Employees in March",
    "month_4": "Employees in April",
    "month_5": "Employees in May",
    "month_6": "Employees in June",
    "month_7": "Employees in July",
    "month_8": "Employees in August",
    "month_9": "Employees in September",
    "month_10": "Employees in October",
    "month_11": "Employees in November",
    "month_12": "Employees in December",
    "Q1_Average": "Average employees in Q1",
    "Q2_Average": "Average employees in Q2",
    "Q3_Average": "Average employees in Q3",
    "Q4_Average": "Average employees in Q4",
    "AVG_N_EMPLOYEES_2": "Yearly average employees",
    "MAX_N_EMPLOYEES_2": "Max employees in a month (yearly)",
    "MIN_N_EMPLOYEES_2": "Min employees in a month (yearly)",
    "Yearly_Average": "Yearly employee average",
    "Yearly_StdDev": "Yearly employee standard deviation",
    "Yearly_Median": "Median employee count for the year",
    "Lag_Q1": "Previous Q1 avg employees",
    "Lag_Q2": "Previous Q2 avg employees",
    "Lag_Q3": "Previous Q3 avg employees",
    "Lag_Q4": "Previous Q4 avg employees",
    "3-Month Rolling Average": "Rolling 3-month avg of employees",
    "6-Month Rolling Average": "Rolling 6-month avg of employees",
    "12-Month Rolling Average": "Rolling 12-month avg of employees",
    "MAX_EMPLOYEE_CHANGE_2": "Change in max employees (yearly)",
    "EMPLOYEE_CHANGE_2": "Change in yearly average employees",
    "PERCENT_CHANGE_2": "Percentage change in yearly average employees",
    "MOMENTUM_2": "Change in yearly employee count change",
    "supplier_COUNT_mean": "Avg number of transactions per supplier",
    "supplier_COUNT_std": "Std dev in number of transactions per supplier",
    "supplier_TOTAL_PRICE_SUM_mean": "Total transaction value per supplier (mean)",
    "supplier_TOTAL_PRICE_SUM_std": "Variability in total transaction value per supplier",
    "supplier_TOTAL_VAT_SUM_mean": "Total VAT amount per supplier (mean)",
    "supplier_TOTAL_VAT_SUM_std": "Variability in total VAT amount per supplier",
    "supplier_TOTAL_VAT_MAX_max": "Max VAT amount in a transaction per supplier",
    "supplier_TOTAL_VAT_MAX_std": "Variability in the max VAT amount per supplier",
    "supplier_TOTAL_VAT_MIN_min": "Min VAT amount in a transaction per supplier",
    "supplier_TOTAL_VAT_MIN_std": "Variability in the min VAT amount per supplier",
    "buyer_COUNT_mean": "Avg number of transactions per buyer",
    "buyer_COUNT_std": "Std dev in number of transactions per buyer",
    "buyer_TOTAL_PRICE_SUM_mean": "Total transaction value per buyer (mean)",
    "buyer_TOTAL_PRICE_SUM_std": "Variability in total transaction value per buyer",
    "buyer_TOTAL_VAT_SUM_mean": "Total VAT amount per buyer (mean)",
    "buyer_TOTAL_VAT_SUM_std": "Variability in total VAT amount per buyer",
    "buyer_TOTAL_VAT_MAX_max": "Max VAT amount in a transaction per buyer",
    "buyer_TOTAL_VAT_MAX_std": "Variability in the max VAT amount per buyer",
    "buyer_TOTAL_VAT_MIN_min": "Min VAT amount in a transaction per buyer",
    "buyer_TOTAL_VAT_MIN_std": "Variability in the min VAT amount per buyer",
    "still_in_business": "Business is active",
    "Years_in_business": "Years since business registration",
    "level1_A41": "Sector-level avg for gross income (A41)",
    "level1_A85": "Sector-level avg for taxable profit or tax loss (A85)",
    "level1_A84": "Sector-level avg for total reductions (A84)",
    "level1_A50": "Sector-level avg for administrative costs (A50)",
    "level1_7a": "Sector-level avg for 20% VAT taxable base (7a)",
    "level1_var1": "Sector-level avg for share of 20% VAT taxable base (var1)",
    "level1_var2": "Sector-level avg for share of 16.67% VAT taxable base (var2)",
    "level1_var3": "Sector-level avg for share of 0% VAT transactions (var3)",
    "level1_var4": "Sector-level avg for Article 2 VAT transactions (var4)",
    "level1_var5": "Sector-level avg for zero-rated VAT transactions ratio (var5)",
    "level1_var6": "Sector-level avg for VAT credit to adjusted VAT base ratio (var6)",
    "level1_var7": "Sector-level avg for VAT credit to total acquisitions ratio (var7)",
    "level1_var8": "Sector-level avg for debit feature (var8)",
    "level1_var9": "Sector-level avg for VAT credit adjustments (var9)",
    "level1_AVG_N_EMPLOYEES": "Sector-level avg for number of employees",
    "level1_AUDIT_ANY": "Sector-level avg for audit occurrences",
    "level1_FRAUD_ANY": "Sector-level avg for fraud occurrences",
}


mapping_short = {
    "RESIDENT_NO_RESIDENT": "Resident / non-resident",
    "A6": "6. Income from selling goods",
    "A7": "7. Income from selling production",
    "A8": "8. Income from performing work",
    "A9": "9. Income from providing services",
    "A9_1": "9.1 Income from freight services by entrepreneurs",
    "A10": "10. Income from mediation agreements",
    "A11": "11. Income from selling fixed assets",
    "A12": "12. Income from selling intangible assets",
    "A13": "13. Income from selling other assets",
    "A14": "14. Income from dividends",
    "A15": "15. Interest income from loans",
    "A16": "16. Interest income from provided loans",
    "A17": "17. Interest income from financial lease",
    "A18": "18. Income from rent or operating lease fees",
    "A19": "19. Income from royalties",
    "A20": "20. Income from free cash received",
    "A21": "21. Income from land received for free",
    "A22": "22. Income from other assets received free",
    "A23": "23. Income from assets by court decisions",
    "A24": "24. Income from forfeited assets recognized by law",
    "A25": "25. Income from surplus inventory found",
    "A26": "26. Income from discounted or forgiven obligations",
    "A27": "27. Income from discounts or pardoned obligations",
    "A28": "28. Income from damages or losses",
    "A29": "29. Income from penalties, fines, and sanctions",
    "A30": "30. Income from adjustments to prior deductions",
    "A31": "31. Income from written-off payables",
    "A32": "32. Income from repayment of written-off receivables",
    "A33": "33. Income from adjusted reserves for receivables",
    "A34": "34. Income from recovering bad assets or securities",
    "A35": "35. Income from reducing unneeded asset reserves",
    "A36": "36. Income from insurance technical reserves",
    "A37": "37. Income from reinsurance commissions",
    "A38": "38. Income from derivative financial instruments",
    "A39": "39. Income from VAT adjustments",
    "A40": "40. Other income",
    "A41": "41. Gross income (sum of items 6-40)",
    "A41A": "1) Income from patent-taxable activities",
    "A41B": "2) Income from joint activities",
    "A41C": "3) Income from production in border zones",
    "A42": "42. Initial cost of supplied goods",
    "A43": "43. Costs related to producing goods",
    "A44": "44. Costs related to performing work",
    "A45": "45. Costs related to providing services",
    "A46": "46. Costs related to mediation agreements",
    "A47": "47. Book value of sold fixed assets",
    "A48": "48. Book value of sold intangible assets",
    "A49": "49. Book value of other sold assets",
    "A50": "50. Administrative costs",
    "A50_1": "50.1 Business trips outside Armenia",
    "A50_2": "50.2 Business trips within Armenia",
    "A50_3": "50.3 Representative expenses",
    "A50_4": "50.4 Management services expenses",
    "A50_5": "50.5 Consulting services expenses",
    "A50_6": "50.6 Information services expenses",
    "A51": "51. Sales costs",
    "A51_1": "51.1 Advertising expenses",
    "A51_2": "51.2 Marketing costs",
    "A52": "52. Non-production expenses",
    "A53": "53. Financial expenses",
    "A53_1": "53.1 Interest on loans from banks",
    "A53_2": "53.2 Interest on loans from non-bank entities",
    "A54": "54. Costs for social or cultural events",
    "A55": "55. Insurance and reinsurance costs",
    "A56": "56. Rental fees or service costs",
    "A57": "57. Costs for damage compensation",
    "A58": "58. Costs for penalties and sanctions",
    "A59": "59. Non-refundable taxes, duties, or fees",
    "A60": "60. Costs deducted from VAT amounts",
    "A61": "61. Other costs",
    "A62": "62. Total costs (items 42-61)",
    "A63": "63. Losses from natural causes",
    "A64": "64. Losses from quality issues",
    "A65": "65. Random losses",
    "A66": "66. Other losses",
    "A67": "67. Total losses (items 63-66)",
    "A68": "68. Deductions from invalid transactions",
    "A69": "69. Deductions for bad debt allowances",
    "A70": "70. Amounts exceeding bad debt reserves",
    "A71": "71. Repayment of written-off debts",
    "A72": "72. Reserves for possible asset losses",
    "A73": "73. Insurance or reinsurance payments",
    "A74": "74. Costs for insurance technical reserves",
    "A75": "75. Losses from counterfeit banknotes",
    "A76": "76. Tax losses from the prior 5 years",
    "A77": "77. Value of assets given to non-profits",
    "A78": "78. Deduction for employing disabled workers",
    "A79": "79. Payments to registered financial instruments",
    "A80": "80. Dividends paid to resident taxpayers",
    "A81": "81. Retirement fees for entrepreneurs or notaries",
    "A82": "82. Other deductions",
    "A83": "83. Total reductions (items 68-82)",
    "A84": "84. Total reductions (items 62 + 67 + 83)",
    "A84_1": "1) Reductions from patent-taxable activities",
    "A84_2": "2) Reductions from joint activities",
    "A84_3": "3) Reductions for production in border zones",
    "A85": "85. Taxable profit or tax loss after reductions",
    "A86": "86. Tax benefits reducing taxable profit",
    "A87": "87. Taxable profit after applying tax benefits",
    "A88": "88. Calculated profit tax for the year",
    "A89": "89. Government-approved profit tax benefits",
    "A90": "90. Profit tax reductions for specific citizens",
    "A91": "91. Total profit tax reductions (items 89 + 90)",
    "A92": "92. Profit tax after reductions",
    "A93": "93. Undeducted foreign profit tax from prior years",
    "A94": "94. Foreign profit tax for the current year",
    "A95": "95. Deducted foreign profit tax for current year",
    "A96": "96. Undeducted foreign profit tax carried forward",
    "A97": "97. Profit tax withheld for permanent sites",
    "A98": "98. Final profit tax after deductions",
    "A99": "99. Profit tax on income not from permanent sites",
    "A100": "100. Total profit tax (items 98 + 99)",
    "A101": "101. Total prepayments toward profit tax",
    "A102": "102. Profit tax after deducting prepayments",
    "A103": "103. Minimum profit tax not yet deducted",
    "A104": "104. Final profit tax payable",
    "A105": "105. Minimum profit tax carried forward",
    "A106": "106. Profit tax eligible for reimbursement",
    "A107": "107. Profit tax for entrepreneurs and notaries",
    "v7a": "7. 20% VAT taxable base maintenance [a]",
    "v7b": "7. 20% VAT taxable transactions [b] (VAT Credit)",
    "v8a1": "8. Reduction of adjustable tax account deals [a]",
    "v8a2": "8. Determination of adjustment tax accounts [b]",
    "v8b1": "8. Adjusted tax account additions [a]",
    "v8b2": "8. Adjusted tax account additions [b]",
    "v9a": "9. 16.67% taxable base [a]",
    "v9b": "9. 16.67% taxable base [b] (VAT Credit)",
    "v10": "10. Other tax liability on VAT",
    "v111": "11. Reduction of adjustable accounts from supplier",
    "v112": "11. Additions of adjustable accounts from supplier",
    "v12": "12. Transactions at 0% VAT rate (Article 2)",
    "v13": "13. Article 2 of the Tax Code (VAT)",
    "v14": "14. Clause invalid from Jan 1, 2020",
    "v15a": "15. Adjustment of VAT liabilities [A]: Addition",
    "v15b": "15. Adjustment of VAT liabilities [B]: Reduction",
    "v16a": "16. Total VAT credit [A]. Taxation base",
    "v16b": "16. Total VAT credit [B]. VAT credit",
    "v17a": "17. Value of goods imported [A]",
    "v17b": "17. VAT debit of goods imported [B]",
    "v18a": "18. Cost of goods/services in RA [A]",
    "v18b": "18. VAT debit of goods/services in RA [B]",
    "v19a1": "19. Deduction of adjusting accounts [A]",
    "v19b1": "19. Deduction of adjusting accounts [B]",
    "v19a2": "19. Addition of adjusting accounts [A]",
    "v19b2": "19. Addition of adjusting accounts [B]",
    "v20a": "20. Total VAT adjustment [A]: Addition",
    "v20b": "20. Total VAT adjustment [B]: Reduction",
    "v21a": "21. Total VAT debit ([A]: Positive)",
    "v21b": "21. Total VAT debit ([B]: Negative)",
    "v22a": "22. Imported goods VAT (Tax base) [A]",
    "v22b": "22. Imported goods VAT (Calculated) [B]",
    "v23a": "23. VAT for reporting [A]: payable to state budget",
    "v23b": "23. VAT for reporting [B]: reimbursed from state",
    "v24": "24. Excise tax base and calculated amount",
    "v25": "25. Excise tax (reduction) for excise goods",
    "v26": "26. Excise tax (addition) for excise goods",
    "v27": "27. Calculated excise tax amount (excise tax credit)",
    "v281": "28.1. Excise tax (adjusting accounts): reduction",
    "v282": "28.2. Excise tax (adjusting accounts): addition",
    "v29": "29. Base of expropriated goods exempt from excise",
    "v30": "30. Excise tax for imported raw materials",
    "v31": "31. Excise tax for purchased raw materials",
    "v32a": "32. Excise tax adjustment [A]: Addition",
    "v32b": "32. Excise tax adjustment [B]: Reduction",
    "v33a": "33. Excise tax debit [A]: Positive",
    "v33b": "33. Excise tax debit [B]: Negative",
    "v34a": "34. Excise tax payable [A]",
    "v34b": "34. Excise tax reimbursed [B]",
    "v7a_mean": "Avg 20% VAT taxable base",
    "v7b_mean": "Avg 20% VAT taxable (credit)",
    "v8a1_mean": "Avg reduction adjustable accounts (base)",
    "v8a2_mean": "Avg determination adjustment accounts (credit)",
    "v8b1_mean": "Avg adjusted tax account additions (base)",
    "v8b2_mean": "Avg adjusted tax account additions (credit)",
    "v9a_mean": "Avg 16.67% taxable base (month)",
    "v9b_mean": "Avg 16.67% taxable (credit)",
    "v10_mean": "Avg other VAT liability",
    "v111_mean": "Avg reduction adjustable accounts",
    "v112_mean": "Avg additions adjustable accounts",
    "v12_mean": "Avg 0% VAT rate transactions",
    "v13_mean": "Avg Article 2 VAT transactions",
    "v14_mean": "Avg invalid clause transactions",
    "v15a_mean": "Avg VAT liability adjustment (add)",
    "v15b_mean": "Avg VAT liability adjustment (reduce)",
    "v16a_mean": "Avg total VAT credit (base)",
    "v16b_mean": "Avg total VAT credit",
    "v17a_mean": "Avg value imported goods",
    "v17b_mean": "Avg VAT debit imported goods",
    "v18a_mean": "Avg cost goods/services in RA",
    "v18b_mean": "Avg VAT debit goods/services in RA",
    "v19a1_mean": "Avg deduction adjusting accounts (value)",
    "v19b1_mean": "Avg deduction adjusting accounts (VAT)",
    "v19a2_mean": "Avg addition adjusting accounts (value)",
    "v19b2_mean": "Avg addition adjusting accounts (VAT)",
    "v20a_mean": "Avg VAT adjustment (add)",
    "v20b_mean": "Avg VAT adjustment (reduce)",
    "v21a_mean": "Avg total VAT debit (pos)",
    "v21b_mean": "Avg total VAT debit (neg)",
    "v22a_mean": "Avg imported goods VAT base",
    "v22b_mean": "Avg imported goods VAT amount",
    "v23a_mean": "Avg VAT payable to budget",
    "v23b_mean": "Avg VAT reimbursed from budget",
    "v24_mean": "Avg excise tax base & amount",
    "v25_mean": "Avg excise tax (reduction)",
    "v26_mean": "Avg excise tax (addition)",
    "v27_mean": "Avg excise tax credit",
    "v281_mean": "Avg excise tax adjusting (reduce)",
    "v282_mean": "Avg excise tax adjusting (add)",
    "v29_mean": "Avg base expropriated goods",
    "v30_mean": "Avg excise tax imported raw",
    "v31_mean": "Avg excise tax purchased raw",
    "v32a_mean": "Avg excise tax adj (add)",
    "v32b_mean": "Avg excise tax adj (reduce)",
    "v33a_mean": "Avg excise tax debit (pos)",
    "v33b_mean": "Avg excise tax debit (neg)",
    "v34a_mean": "Avg excise tax payable",
    "v34b_mean": "Avg excise tax reimbursed",
    "A9_ALL": "Sum A9 and A9_1 income",
    "ALL_105": "Sum A11, A12, A13 income",
    "ALL_106": "Sum A15, A16, A17 interest income",
    "ALL_113": "Sum A20, A21, A22, A23 income",
    "ALL_117": "Sum A24, A25 income",
    "ALL_203": "Sum A45, A46 costs",
    "ALL_204": "Sum A47, A48, A49 book values",
    "profitability": "Profitability ratio",
    "admin_ratio": "Admin costs ratio (A50)",
    "A50_lagged": "Lagged A50: Admin costs",
    "A85_lagged": "Lagged A85: Taxable profit/loss",
    "A84_lagged": "Lagged A84: Total reductions",
    "A41_lagged": "Lagged A41: Gross income",
    "has_new_financials": "Has Shahuthark data",
    "has_financial": "Has VAT data",
    "var1": "Prop 20% VAT base in total VAT sales",
    "var1_std": "Var in prop 20% VAT base",
    "var2": "Prop 16.67% VAT base in total VAT sales",
    "var2_std": "Var in prop 16.67% VAT base",
    "var3": "Prop 0% VAT in total VAT sales",
    "var3_std": "Var in prop 0% VAT",
    "var4": "Prop Article 2 VAT in total sales",
    "var4_std": "Var in Article 2 VAT prop",
    "var5": "Ratio zero-rate VAT to total VAT credit",
    "var5_std": "Var in ratio zero-rate to credit",
    "var6": "Ratio total VAT credit to adjusted 20% base",
    "var6_std": "Var in ratio VAT credit/20% base",
    "var7": "Ratio VAT credit to total acquisitions",
    "var7_std": "Var in ratio credit/acquisitions",
    "var8": "Share of VAT debit adjustments to acquisitions",
    "var8_std": "Var in share VAT debit adj",
    "var9": "Prop VAT credit adjustments to total VAT credit",
    "var9_std": "Var in prop credit adj",
    "var10": "Prop reductions in VAT credit adj",
    "var10_std": "Var in prop reductions credit adj",
    "n_MONTH_filed": "Count of filed months",
    "TOTAL": "Total of various VAT bases",
    "TOTAL_CHANGE": "Change in TOTAL vs prev year",
    "7a_CHANGE": "Change in 20% VAT base vs prev year",
    "var1_CHANGE": "Change in prop 20% VAT base vs prev year",
    "var2_CHANGE": "Change in prop 16.67% VAT base vs prev year",
    "var3_CHANGE": "Change in prop 0% VAT vs prev year",
    "var4_CHANGE": "Change in Article 2 VAT prop vs prev year",
    "var5_CHANGE": "Change in zero-rate/credit ratio vs prev year",
    "var6_CHANGE": "Change in credit/adjusted 20% ratio vs prev year",
    "var7_CHANGE": "Change in credit/acquisitions ratio vs prev year",
    "var8_CHANGE": "Change in VAT debit adj share vs prev year",
    "var9_CHANGE": "Change in credit adj ratio vs prev year",
    "AVG_N_EMPLOYEES": "Avg employees",
    "EMPLOYEE_CHANGE": "Change in avg employees",
    "PERCENT_CHANGE": "Percent change in employees",
    "ROLLING_MEAN_EMP": "4-period rolling avg employees",
    "ROLLING_STD_EMP": "4-period rolling std employees",
    "MOMENTUM": "Change in employee count change",
    "month_1": "Employees in January",
    "month_2": "Employees in February",
    "month_3": "Employees in March",
    "month_4": "Employees in April",
    "month_5": "Employees in May",
    "month_6": "Employees in June",
    "month_7": "Employees in July",
    "month_8": "Employees in August",
    "month_9": "Employees in September",
    "month_10": "Employees in October",
    "month_11": "Employees in November",
    "month_12": "Employees in December",
    "Q1_Average": "Avg employees Q1",
    "Q2_Average": "Avg employees Q2",
    "Q3_Average": "Avg employees Q3",
    "Q4_Average": "Avg employees Q4",
    "AVG_N_EMPLOYEES_2": "Yearly avg employees",
    "MAX_N_EMPLOYEES_2": "Max monthly employees (year)",
    "MIN_N_EMPLOYEES_2": "Min monthly employees (year)",
    "Yearly_Average": "Yearly employee avg",
    "Yearly_StdDev": "Yearly employee std dev",
    "Yearly_Median": "Yearly employee median",
    "Lag_Q1": "Prev Q1 avg employees",
    "Lag_Q2": "Prev Q2 avg employees",
    "Lag_Q3": "Prev Q3 avg employees",
    "Lag_Q4": "Prev Q4 avg employees",
    "3-Month Rolling Average": "3-mo rolling avg employees",
    "6-Month Rolling Average": "6-mo rolling avg employees",
    "12-Month Rolling Average": "12-mo rolling avg employees",
    "MAX_EMPLOYEE_CHANGE_2": "Change in max employees (year)",
    "EMPLOYEE_CHANGE_2": "Change in yearly avg employees",
    "PERCENT_CHANGE_2": "Percent change yearly avg employees",
    "MOMENTUM_2": "Change in yearly employee momentum",
    "supplier_COUNT_mean": "Avg transactions per supplier",
    "supplier_COUNT_std": "Std dev transactions per supplier",
    "supplier_TOTAL_PRICE_SUM_mean": "Avg total value per supplier",
    "supplier_TOTAL_PRICE_SUM_std": "Var in total value per supplier",
    "supplier_TOTAL_VAT_SUM_mean": "Avg total VAT per supplier",
    "supplier_TOTAL_VAT_SUM_std": "Var in total VAT per supplier",
    "supplier_TOTAL_VAT_MAX_max": "Max VAT per supplier",
    "supplier_TOTAL_VAT_MAX_std": "Var in max VAT per supplier",
    "supplier_TOTAL_VAT_MIN_min": "Min VAT per supplier",
    "supplier_TOTAL_VAT_MIN_std": "Var in min VAT per supplier",
    "buyer_COUNT_mean": "Avg transactions per buyer",
    "buyer_COUNT_std": "Std dev transactions per buyer",
    "buyer_TOTAL_PRICE_SUM_mean": "Avg total value per buyer",
    "buyer_TOTAL_PRICE_SUM_std": "Var in total value per buyer",
    "buyer_TOTAL_VAT_SUM_mean": "Avg total VAT per buyer",
    "buyer_TOTAL_VAT_SUM_std": "Var in total VAT per buyer",
    "buyer_TOTAL_VAT_MAX_max": "Max VAT per buyer",
    "buyer_TOTAL_VAT_MAX_std": "Var in max VAT per buyer",
    "buyer_TOTAL_VAT_MIN_min": "Min VAT per buyer",
    "buyer_TOTAL_VAT_MIN_std": "Var in min VAT per buyer",
    "still_in_business": "Business is active",
    "Years_in_business": "Years since registration",
    "level1_A41": "Sector avg gross income (A41)",
    "level1_A85": "Sector avg taxable profit/loss (A85)",
    "level1_A84": "Sector avg total reductions (A84)",
    "level1_A50": "Sector avg admin costs (A50)",
    "level1_7a": "Sector avg 20% VAT base (7a)",
    "level1_var1": "Sector avg prop 20% VAT",
    "level1_var2": "Sector avg prop 16.67% VAT",
    "level1_var3": "Sector avg prop 0% VAT",
    "level1_var4": "Sector avg Article 2 VAT prop",
    "level1_var5": "Sector avg zero-rated VAT ratio",
    "level1_var6": "Sector avg credit/20% ratio",
    "level1_var7": "Sector avg credit/acquisitions ratio",
    "level1_var8": "Sector avg VAT debit feature",
    "level1_var9": "Sector avg VAT credit adjustments",
    "level1_AVG_N_EMPLOYEES": "Sector avg employees",
    "level1_AUDIT_ANY": "Sector avg audits",
    "level1_FRAUD_ANY": "Sector avg fraud occurrences",
}

mapping_short_arm = {
    "RESIDENT_NO_RESIDENT": "Ռեզիդենտ/Ոչ ռեզիդենտ",
    "A6": "6. Ապրանքների մատակարարումից եկամուտը",
    "A7": "7. Արտադրանքի մատակարարումից եկամուտը",
    "A8": "8. Աշխատանքների կատարումից եկամուտը",
    "A9": "9. Ծառայությունների մատուցումից եկամուտը",
    "A9_1": "9.1 Անհատ ձեռնարկատերերի ֆրախտի դիմաց ստացվող եկամուտը",
    "A10": "10. Միջնորդական պայմանագրերի գործարքներից եկամուտը",
    "A11": "11. Հիմնական միջոցների օտարումից եկամուտը",
    "A12": "12. Ոչ նյութական ակտիվների օտարումից եկամուտը",
    "A13": "13. Այլ ակտիվների օտարումից եկամուտը",
    "A14": "14. Շահաբաժիններից եկամուտը",
    "A15": "15. Վարկերի տրամադրումից տոկոսային եկամուտը",
    "A16": "16. Փոխառությունների տրամադրումից տոկոսային եկամուտը",
    "A17": "17. Ֆինանսական վարձակալությունից տոկոսային եկամուտը",
    "A18": "18. Գործառնական վարձակալությունից վարձակալական վճարից և (կամ) սերվիտուտի վճարից եկամուտը",
    "A19": "19. Ռոյալթիներից եկամուտը",
    "A20": "20. Անհատույց ստացված դրամական միջոցներից եկամուտը",
    "A21": "21. Անհատույց ստացված հողամասերից եկամուտը",
    "A22": "22. Անհատույց ստացված այլ ակտիվներից եկամուտը",
    "A23": "23. Դատարանի որոշումների հիման վրա ակտիվներից եկամուտը",
    "A24": "24. Տիրազուրկ ակտիվներից եկամուտը օրենսդրությամբ սահմանված կարգով",
    "A25": "25. Գույքագրման ժամանակ հայտնաբերված գույքի ավելցուկից եկամուտը",
    "A26": "26. Փաստացի առաջացած (առկա) պարտավորությունների զեղչումից կամ ներումից ստացվող եկամուտը",
    "A27": "27. Զեղչումից կամ ներումից ստացվող եկամուտը",
    "A28": "28. Պատճառված վնասի (կրած կորստի) հատուցումից եկամուտը",
    "A29": "29. Տույժերի, տուգանքների և գույքային այլ պատժամիջոցների տեսքով եկամուտը",
    "A30": "30. Նախորդ հաշվետու ժամանակաշրջաններում նվազեցումների վերաձևակերպումից եկամուտը",
    "A31": "31. Հարկման նպատակով դուրս գրման ենթակա կրեդիտորական պարտքերից եկամուտը",
    "A32": "32. Նախկինում դուրս գրված անհուսալի դեբիտորական պարտքերի մարումից եկամուտը",
    "A33": "33. Դուրս չգրված դեբիտորական պարտքերի մարման դեպքում` պահուստին կատարված մասհանումներից և պահուստաֆոնդի ճշգրտումից եկամուտը",
    "A34": "34. Անհուսալի ակտիվների և ինվեստիցիոն արժեթղթերի` հաշվեկշռում վերականգնման արդյունքում հաշվեգրված եկամուտը",
    "A35": "35. Ակտիվների պահուստների նվազեցման գծով հաշվեգրված եկամուտը",
    "A36": "36. Ապահովագրական ընկերությունների տեխնիկական պահուստներից եկամուտը",
    "A37": "37. Վերաապահովագրության փոխանցված պայմանագրերից ստացվող կոմիսիոն վարձատրությունից եկամուտը",
    "A38": "38. Ածանցյալ ֆինանսական գործիքներից եկամուտը",
    "A39": "39. Հաշվանցման (պակասեցման) ենթակա ԱԱՀ-ի գումարներին ավելացվող գումարներից եկամուտը",
    "A40": "40. Այլ եկամուտները",
    "A41": "41. Համախառն եկամուտը (6-40-րդ կետեր)",
    "A41A": "1) Արտոնագրային հարկով հարկվող գործունեությունից եկամուտը",
    "A41B": "2) Համատեղ գործունեությունից եկամուտը",
    "A41C": "3) Սահմանամերձ բնակավայրերում գործունեության շրջանակներում եկամուտը",
    "A42": "42. Մատակարարված ապրանքների սկզբնական արժեքը",
    "A43": "43. Մատակարարված արտադրանքի արտադրության հետ կապված ծախսը",
    "A44": "44. Աշխատանքների կատարման հետ կապված ծախսը",
    "A45": "45. Ծառայությունների մատուցման հետ կապված ծախսը",
    "A46": "46. Միջնորդական պայմանագրերի գործարքների հետ կապված ծախսը",
    "A47": "47. Օտարված հիմնական միջոցների հաշվեկշռային արժեքը",
    "A48": "48. Օտարված ոչ նյութական ակտիվների հաշվեկշռային արժեքը",
    "A49": "49. Օտարված այլ ակտիվների հաշվեկշռային արժեքը",
    "A50": "50. Վարչական ծախսերը",
    "A50_1": "50.1 ՀՀ տարածքից դուրս գործուղման հետ կապված ծախսերը",
    "A50_2": "50.2 ՀՀ տարածքում գործուղման հետ կապված ծախսերը",
    "A50_3": "50.3 Ներկայացուցչական ծախսերը",
    "A50_4": "50.4 Կառավարման ծառայությունների գծով ծախսերը",
    "A50_5": "50.5 Խորհրդատվական ծառայությունների գծով ծախսերը",
    "A50_6": "50.6 Տեղեկատվական ծառայությունների գծով ծախսերը",
    "A51": "51. Իրացման ծախսերը",
    "A51_1": "51.1 Գովազդի գծով ծախսերը",
    "A51_2": "51.2 Մարկետինգի գծով ծախսերը",
    "A52": "52. Ոչ արտադրական բնույթի ծախսերը",
    "A53": "53. Ֆինանսական ծախսերը",
    "A53_1": "53.1 Վարկերի, ինչպես նաև բանկերից և վարկային կազմակերպություններից ներգրավված փոխառությունների գծով տոկոսը",
    "A53_2": "53.2 Բանկ և (կամ) վարկային կազմակերպություն չհամարվող սուբյեկտներից ներգրավված փոխառությունների գծով տոկոսը",
    "A54": "54. Սոցիալ-մշակութային միջոցառումների կազմակերպման և համանման այլ ծախսերը",
    "A55": "55. Ապահովագրական և վերաապահովագրական ծախսը",
    "A56": "56. Վարձակալական վճարի կամ սերվիտուտի գծով ծախսը",
    "A57": "57. Պատճառված վնասի (կրած կորստի) հատուցման գծով ծախսը",
    "A58": "58. Տույժերի, տուգանքների և գույքային այլ պատժամիջոցների տեսքով ծախսը",
    "A59": "59. Չփոխհատուցվող և չպակասեցվող հարկերի,տուրքերի և վճարների գծով ծախսը",
    "A60": "60. Հաշվանցման (պակասեցման) ենթակա ԱԱՀ-ի գումարներից նվազեցվող գումարների գծով ծախսը",
    "A61": "61. Այլ ծախսերը",
    "A62": "62. Ընդամենը ծախսերը (42-61-րդ կետեր)",
    "A63": "63. Բնական կորուստը",
    "A64": "64. Որակական կորուստը",
    "A65": "65. Պատահական կորուստը",
    "A66": "66. Այլ կորուստը",
    "A67": "67. Ընդամենը կորուստները (63-66-րդ կետեր)",
    "A68": "68. Անվավեր ճանաչված գործարքների մասով նվազեցումը",
    "A69": "69. Անհուսալի դեբիտորական պարտքերի դուրսգրման համար պահուստին կատարվող մասհանումները",
    "A70": "70. Անհուսալի դեբիտորական պարտքերի դուրսգրման դեպքում` պահուստին կատարված մասհանումները գերազանցող գումարները",
    "A71": "71. Նախկինում դուրս գրված անհուսալի կրեդիտորական պարտքերի մարման գումարները",
    "A72": "72. հնարավոր կորուստների պահուստներին ուղղված գումարները",
    "A73": "73. Ապահովագրական և վերաապահովագրական հատուցումները",
    "A74": "74. Տեխնիկական պահուստների գծով կատարվող ծախսերը",
    "A75": "75. Կեղծ թղթադրամների և վճարային փաստաթղթերի պատճառով կրած կորուստները",
    "A76": "76. Նախորդ 5 հարկային տարիներին առաջացած հարկային վնասը",
    "A77": "77. Ոչ առևտրային կազմակերպություններին տրամադրված ակտիվների արժեքը",
    "A78": "78. Վարձու աշխատող համարվող յուրաքանչյուր հաշմանդամի համար ստացվող եկամուտներից նվազեցումը",
    "A79": "79. Գրանցված ածանցյալ ֆինանսական գործիքներով կատարվող վճարումների գծով ծախսը",
    "A80": "80. Ռեզիդենտ շահութահարկ վճարողի շահաբաժինները",
    "A81": "81. Անհատ ձեռնարկատիրոջ կամ նոտարի կամավոր կենսաթոշակային վճար",
    "A82": "82. Այլ նվազեցումներ",
    "A83": "83. Ընդամենը այլ նվազեցումները (68-82-րդ կետեր)",
    "A84": "84. Ընդամենը նվազեցումներ (կետեր 62 + 67 + 83)",
    "A84_1": "1) Արտոնագրային հարկով հարկվող գործունեությունից նվազեցումները",
    "A84_2": "2) Համատեղ գործունեությունից նվազեցումները",
    "A84_3": "3) Սահմանամերձ բնակավայրերում գործունեության գծով նվազեցումները",
    "A85": "85. Հարկվող շահույթը կամ հարկային վնասը",
    "A86": "86. Հարկվող շահույթի նվազեցման արտոնությունները",
    "A87": "87. Հարկվող շահույթը` հաշվի առած հարկվող շահույթի նվազեցման արտոնությունները",
    "A88": "88. Հաշվետու տարվա շահութահարկի գումարը",
    "A89": "89. Կառավարության որոշմամբ արտոնությամբ նվազեցվող շահութահարկի գումարը",
    "A90": "90. Առանձին խմբերի քաղաքացիներին արտոնությամբ նվազեցվող շահութահարկի գումարը",
    "A91": "91. Ընդամենը արտոնությամբ նվազեցվող շահութահարկի գումարը (կետեր 89 + 90)",
    "A92": "92. Շահութահարկի գումարը` արտոնությունները նվազեցնելուց հետո",
    "A93": "93. Նախորդ տարիներին օտարերկրյա պետություններում գանձված շահութահարկի չնվազեցված մասը",
    "A94": "94. Հաշվետու տարում օտարերկրյա պետություններում գանձված նվազեցման ենթակա այլ հարկի գումարը",
    "A95": "95. Օտարերկրյա պետություններում գանձված շահութահարկից նվազեցվող գումարը",
    "A96": "96. Օտարերկրյա պետություններում գանձված շահութահարկի հաջորդ տարիներ փոխանցվող գումարը",
    "A97": "97. Մշտական հաստատության համար պահված շահութահարկի գումարը",
    "A98": "98. Շահութահարկի գումարը` նվազեցումներից հետո",
    "A99": "99. Մշտական հաստատությանը չվերագրվող եկամուտների մասով շահութահարկի գումարը",
    "A100": "100. Շահութահարկի ընդհանուր գումար (կետեր 98 + 99)",
    "A101": "101. Շահութահարկի կանխավճարների հանրագումարը",
    "A102": "102. Շահութահարկի գումարը` կանխավճարները նվազեցնելուց հետո",
    "A103": "103. Չհաշվանցված նվազագույն շահութահարկի գումարը",
    "A104": "104. Վճարման ենթակա շահութահարկի գումարը",
    "A105": "105. Հաջորդ տարիներ փոխանցվող` չհաշվանցված նվազագույն շահութահարկի գումարը",
    "A106": "106. Բյուջեից փոխհատուցման ենթակա շահութահարկի գումարը",
    "A107": "107. Անհատ ձեռնարկատերերի և նոտարների շահութահարկի գումարը",
    "v7a": "7. ԱԱՀ-ի 20% դրույքաչափով հարկվող գործարքների [Ա].Հարկման բազա",
    "v7b": "7. ԱԱՀ-ի 20% դրույքաչափով հարկվող գործարքների [Բ].ԱԱՀ կրեդիտ",
    "v8a1": "8. Ճշգրտող հարկային հաշիվներով գործարքների նվազեցում [Ա]",
    "v8a2": "8. Ճշգրտող հարկային հաշիվներով գործարքների նվազեցում [Բ]",
    "v8b1": "8. Ճշգրտող հարկային հաշիվներով գործարքների ավելացում [Ա]",
    "v8b2": "8. Ճշգրտող հարկային հաշիվներով գործարքների ավելացում [Բ]",
    "v9a": "9. ԱԱՀ-ի 16.67% դրույքաչափով հաշվարկվող [Ա].Հարկման բազա",
    "v9b": "9. ԱԱՀ-ի 16.67% դրույքաչափով հաշվարկվող [Բ].ԱԱՀ կրեդիտ",
    "v10": "10. ԱԱՀ-ի գծով այլ հարկային պարտավորություն",
    "v111": "11. Մատակարարի ճշգրտող հարկային հաշիվներով գործարքների նվազեցում",
    "v112": "11. Մատակարարի ճշգրտող հարկային հաշիվներով գործարքների ավելացում",
    "v12": "12. ԱԱՀ-ի 0-ական դրույքաչափով հարկվող գործարքներ (Հոդված 2)",
    "v13": "13. ԱԱՀ-ից ազատված գործարքներ (Հոդված 2)",
    "v14": "14. Կետն ուժը կորցրած է ճանաչվել 2020թ. հունվարի 1-ից",
    "v15a": "15. ԱԱՀ-ի կրեդիտի ավելացում",
    "v15b": "15. ԱԱՀ-ի կրեդիտի նվազեցում",
    "v16a": "16. Ընդամենը ԱԱՀ-ի կրեդիտ [Ա].Հարկման բազա",
    "v16b": "16. Ընդամենը ԱԱՀ-ի կրեդիտ [Բ].ԱԱՀ կրեդիտ",
    "v17a": "17. ՀՀ տարածք ներմուծված ապրանքների [Ա].Արժեք",
    "v17b": "17. ՀՀ տարածք ներմուծված ապրանքների [Բ].ԱԱՀ դեբետ",
    "v18a": "18. ՀՀ տարածքում ձեռք բերված ապրանքների և ծառայությունների [Ա].Արժեք",
    "v18b": "18. ՀՀ տարածքում ձեռք բերված ապրանքների և ծառայությունների [Բ].ԱԱՀ դեբետ",
    "v19a1": "19. Ձեռքբերումներին վերաբերող ճշգրտող հարկային հաշիվներով գործարքների 1) նվազեցում [Ա].Արժեք",
    "v19b1": "19. Ձեռքբերումներին վերաբերող ճշգրտող հարկային հաշիվներով գործարքների 1) նվազեցում [Բ].ԱԱՀ դեբետ",
    "v19a2": "19. Ձեռքբերումներին վերաբերող ճշգրտող հարկային հաշիվներով գործարքների 2) ավելացում [Ա].Արժեք",
    "v19b2": "19. Ձեռքբերումներին վերաբերող ճշգրտող հարկային հաշիվներով գործարքների 2) ավելացում [Բ].ԱԱՀ դեբետ",
    "v20a": "20. ԱԱՀ-ի գումարի ճշգրտման ընդհանուր գումարը [Ա].Ավելացում",
    "v20b": "20. ԱԱՀ-ի գումարի ճշգրտման ընդհանուր գումարը [Ա].Պակասեցում",
    "v21a": "21. Ընդամենը ԱԱՀ-ի դեբետ [Ա].դրական",
    "v21b": "21. Ընդամենը ԱԱՀ-ի դեբետ [Բ].բացասական",
    "v22a": "22. Ներմուծված ապրանքների ԱԱՀ [Ա].Հարկման բազա",
    "v22b": "22. Ներմուծված ապրանքների ԱԱՀ [Բ].Հաշվարկված ԱԱՀ գումար",
    "v23a": "23. Հաշվարկված ԱԱՀ [Ա]. Պետական բյուջե վճարման ենթակա",
    "v23b": "23. Հաշվարկված ԱԱՀ [Բ]: Պետական բյուջեից փոխհատուցման ենթակա",
    "v24": "24. Ակցիզային հարկի հարկման բազան և հաշվարկված ակցիզային հարկի գումարը",
    "v25": "25. Ճշգրտող հարկային հաշիվներում ակցիզային հարկի հարկման բազան և ակցիզային հարկի գումարը (նվազեցում)",
    "v26": "26. Ճշգրտող հարկային հաշիվներում ակցիզային հարկի հարկման բազան և ակցիզային հարկի գումարը (ավելացում)",
    "v27": "27. Հաշվարկված ակցիզային հարկի գումար",
    "v281": "28.1. Ճշգրտող հարկային հաշիվներով գործարքների մասով ակցիզային հարկի գումար 1) նվազեցում",
    "v282": "28.2. Ճշգրտող հարկային հաշիվներով գործարքների մասով ակցիզային հարկի գումար 2) ավելացում",
    "v29": "29. Ակցիզային հարկից ազատված` օտարված ապրանքների հարկման բազա",
    "v30": "30. Ներմուծված հումքի մասով ակցիզային հարկի գումար",
    "v31": "31. Ձեռք բերված հումքի մասով ակցիզային հարկի գումար",
    "v32a": "32. Ակցիզային հարկի ճշգրտման ընդհանուր գումար [Ա].Ավելացում",
    "v32b": "32. Ակցիզային հարկի ճշգրտման ընդհանուր գումար [Բ].Պակասեցում",
    "v33a": "33. Ակցիզային հարկի դեբետ [Ա].դրական",
    "v33b": "33. Ակցիզային հարկի դեբետ [Բ].բացասական",
    "v34a": "34. Պետական բյուջե վճարման ենթակա ակցիզային հարկի գումարը [Ա]",
    "v34b": "34. Պետական բյուջեից փոխհատուցման ենթակա ակցիզային հարկի գումարը [Բ]",
    "v7a_mean": "Միջին - 7. ԱԱՀ-ի 20% դրույքաչափով հարկվող գործարքների [Ա].Հարկման բազա",
    "v7b_mean": "Միջին - 7. ԱԱՀ-ի 20% դրույքաչափով հարկվող գործարքների [Բ].ԱԱՀ կրեդիտ",
    "v8a1_mean": "Միջին - 8. Ճշգրտող հարկային հաշիվներով գործարքների նվազեցում [Ա].Հարկման բազա",
    "v8a2_mean": "Միջին - 8. Ճշգրտող հարկային հաշիվներով գործարքների նվազեցում [Բ].ԱԱՀ կրեդիտ",
    "v8b1_mean": "Միջին - 8. Ճշգրտող հարկային հաշիվներով գործարքների ավելացում [Ա].Հարկման բազա",
    "v8b2_mean": "Միջին - 8. Ճշգրտող հարկային հաշիվներով գործարքների ավելացում [Բ].ԱԱՀ կրեդիտ",
    "v9a_mean": "Միջին - 9. ԱԱՀ-ի 16.67% դրույքաչափով հաշվարկվող [Ա].Հարկման բազա",
    "v9b_mean": "Միջին - 9. ԱԱՀ-ի 16.67% դրույքաչափով հաշվարկվող [Բ].ԱԱՀ կրեդիտ",
    "v10_mean": "Միջին - 10. ԱԱՀ-ի գծով այլ հարկային պարտավորություն",
    "v111_mean": "Միջին - 11. Մատակարարի ճշգրտող հարկային հաշիվներով գործարքների նվազեցում",
    "v112_mean": "Միջին - 11. Մատակարարի ճշգրտող հարկային հաշիվներով գործարքների ավելացում",
    "v12_mean": "Միջին - 12. ԱԱՀ-ի 0-ական դրույքաչափով հարկվող գործարքներ (Հոդված 2)",
    "v13_mean": "Միջին - 13. ԱԱՀ-ից ազատված գործարքներ (Հոդված 2)",
    "v14_mean": "Միջին - 14. Կետն ուժը կորցրած է ճանաչվել 2020թ. հունվարի 1-ից",
    "v15a_mean": "Միջին - 15. ԱԱՀ-ի կրեդիտի ավելացում",
    "v15b_mean": "Միջին - 15. ԱԱՀ-ի կրեդիտի նվազեցում",
    "v16a_mean": "Միջին - 16. Ընդամենը ԱԱՀ-ի կրեդիտ [Ա].Հարկման բազա",
    "v16b_mean": "Միջին - 16. Ընդամենը ԱԱՀ-ի կրեդիտ [Բ].ԱԱՀ կրեդիտ",
    "v17a_mean": "Միջին - 17. ՀՀ տարածք ներմուծված ապրանքների [Ա].Արժեք",
    "v17b_mean": "Միջին - 17. ՀՀ տարածք ներմուծված ապրանքների [Բ].ԱԱՀ դեբետ",
    "v18a_mean": "Միջին - 18. ՀՀ տարածքում ձեռք բերված ապրանքների և ծառայությունների [Ա].Արժեք",
    "v18b_mean": "Միջին - 18. ՀՀ տարածքում ձեռք բերված ապրանքների և ծառայությունների [Բ].ԱԱՀ դեբետ",
    "v19a1_mean": "Միջին - 19. Ձեռքբերումներին վերաբերող ճշգրտող հարկային հաշիվներով գործարքների 1) նվազեցում [Ա].Արժեք",
    "v19b1_mean": "Միջին - 19. Ձեռքբերումներին վերաբերող ճշգրտող հարկային հաշիվներով գործարքների 1) նվազեցում [Բ].ԱԱՀ դեբետ",
    "v19a2_mean": "Միջին - 19. Ձեռքբերումներին վերաբերող ճշգրտող հարկային հաշիվներով գործարքների 2) ավելացում [Ա].Արժեք",
    "v19b2_mean": "Միջին - 19. Ձեռքբերումներին վերաբերող ճշգրտող հարկային հաշիվներով գործարքների 2) ավելացում [Բ].ԱԱՀ դեբետ",
    "v20a_mean": "Միջին - 20. ԱԱՀ-ի գումարի ճշգրտման ընդհանուր գումարը [Ա].Ավելացում",
    "v20b_mean": "Միջին - 20. ԱԱՀ-ի գումարի ճշգրտման ընդհանուր գումարը [Ա].Պակասեցում",
    "v21a_mean": "Միջին - 21. Ընդամենը ԱԱՀ-ի դեբետ [Ա].դրական",
    "v21b_mean": "Միջին - 21. Ընդամենը ԱԱՀ-ի դեբետ [Բ].բացասական",
    "v22a_mean": "Միջին - 22. Ներմուծված ապրանքների ԱԱՀ [Ա].Հարկման բազա",
    "v22b_mean": "Միջին - 22. Ներմուծված ապրանքների ԱԱՀ [Բ].Հաշվարկված ԱԱՀ գումար",
    "v23a_mean": "Միջին - 23. Հաշվարկված ԱԱՀ [Ա]. Պետական բյուջե վճարման ենթակա",
    "v23b_mean": "Միջին - 23. Հաշվարկված ԱԱՀ [Բ]: Պետական բյուջեից փոխհատուցման ենթակա",
    "v24_mean": "Միջին - 24. Ակցիզային հարկի հարկման բազան և հաշվարկված ակցիզային հարկի գումարը",
    "v25_mean": "Միջին - 25. Ճշգրտող հարկային հաշիվներում ակցիզային հարկի հարկման բազան և ակցիզային հարկի գումարը (նվազեցում)",
    "v26_mean": "Միջին - 26. Ճշգրտող հարկային հաշիվներում ակցիզային հարկի հարկման բազան և ակցիզային հարկի գումարը (ավելացում)",
    "v27_mean": "Միջին - 27. Հաշվարկված ակցիզային հարկի գումար",
    "v281_mean": "Միջին - 28.1. Ճշգրտող հարկային հաշիվներով գործարքների մասով ակցիզային հարկի գումար 1) նվազեցում",
    "v282_mean": "Միջին - 28.2. Ճշգրտող հարկային հաշիվներով գործարքների մասով ակցիզային հարկի գումար 2) ավելացում",
    "v29_mean": "Միջին - 29. Ակցիզային հարկից ազատված` օտարված ապրանքների հարկման բազա",
    "v30_mean": "Միջին - 30. Ներմուծված հումքի մասով ակցիզային հարկի գումար",
    "v31_mean": "Միջին - 31. Ձեռք բերված հումքի մասով ակցիզային հարկի գումար",
    "v32a_mean": "Միջին - 32. Ակցիզային հարկի ճշգրտման ընդհանուր գումար [Ա].Ավելացում",
    "v32b_mean": "Միջին - 32. Ակցիզային հարկի ճշգրտման ընդհանուր գումար [Բ].Պակասեցում",
    "v33a_mean": "Միջին - 33. Ակցիզային հարկի դեբետ [Ա].դրական",
    "v33b_mean": "Միջին - 33. Ակցիզային հարկի դեբետ [Բ].բացասական",
    "v34a_mean": "Միջին - 34. Պետական բյուջե վճարման ենթակա ակցիզային հարկի գումարը [Ա]",
    "v34b_mean": "Միջին - 34. Պետական բյուջեից փոխհատուցման ենթակա ակցիզային հարկի գումարը [Բ]",
    "A9_ALL": "Հանրագումար - A9 և A9_1 եկամուտ",
    "ALL_105": "Հանրագումար - A11, A12, A13 եկամուտ",
    "ALL_106": "Հանրագումար - A15, A16, A17 տոկոսային եկամուտ",
    "ALL_113": "Հանրագումար - A20, A21, A22, A23 եկամուտ",
    "ALL_117": "Հանրագումար - A24, A25 եկամուտ",
    "ALL_203": "Հանրագումար - A45, A46 ծախսեր",
    "ALL_204": "Հանրագումար - A47, A48, A49 հաշվեկշռային արժեք",
    "profitability": "Շահութաբերության (A85) և համախառն եկամտի (A41) հարաբերակցությունը",
    "admin_ratio": "Վարչական ծախսերի (A50) և ընդամենը նվազեցումների (A84) հարաբերակցությունը",
    "A50_lagged": "Նախորդ տարվա վարչական ծախսեր (A50)",
    "A85_lagged": "Նախորդ տարվա հարկվող շահույթը կամ հարկային վնասը (A85)",
    "A84_lagged": "Նախորդ տարվա ընդամենը նվազեցումները (A84)",
    "A41_lagged": "Նախորդ տարվա համախառն եկամուտը (A41)",
    "has_new_financials": "Առկա են շահութահարկի տվյալներ",
    "has_financial": "Առկա են ԱԱՀ տվյալներ",
    "var1": "ԱԱՀ-ի 20% դրույքաչափով հարկման բազայի մասնաբաժինը ընդհանուր ԱԱՀ-ով վաճառքներում",
    "var1_std": "Ստանդարտ շեղում - ԱԱՀ-ի 20% դրույքաչափով մասնաբաժինը ընդհանուր ԱԱՀ-ով վաճառքներում",
    "var2": "ԱԱՀ-ի 16.67% դրույքաչափով հարկման բազայի մասնաբաժինը ընդհանուր ԱԱՀ-ով վաճառքներում",
    "var2_std": "Ստանդարտ շեղում - ԱԱՀ-ի 16.67% դրույքաչափով մասնաբաժինը ընդհանուր ԱԱՀ-ով վաճառքներում",
    "var3": "ԱԱՀ-ի 0% դրույքաչափով հարկման բազայի մասնաբաժինը ընդհանուր ԱԱՀ-ով վաճառքներում",
    "var3_std": "Ստանդարտ շեղում - ԱԱՀ-ի 0% դրույքաչափով մասնաբաժինը ընդհանուր ԱԱՀ-ով վաճառքներում",
    "var4": "ԱԱՀ-ի Հոդված 2 հարկման բազայի մասնաբաժինը ընդհանուր ԱԱՀ-ով վաճառքներում",
    "var4_std": "Ստանդարտ շեղում - ԱԱՀ-ի Հոդված 2 հարկման բազայի մասնաբաժինը ընդհանուր ԱԱՀ-ով վաճառքներում",
    "var5": "ԱԱՀ-ի 0-ական դրույքաչափով հարկվող և ԱԱՀ-ից ազատված գործարքների (Հոդված 2) հարաբերակցությունը ընդամենը ԱԱՀ-ի կրեդիտին",
    "var5_std": "Ստանդարտ շեղում - ԱԱՀ-ի 0-ական դրույքաչափով հարկվող և ԱԱՀ-ից ազատված գործարքների (Հոդված 2) հարաբերակցությունը ընդամենը ԱԱՀ-ի կրեդիտին",
    "var6": "Ընդամենը ԱԱՀ կրեդիտ-ի հարաբերակցությունը ճշգրտված 20% բազային",
    "var6_std": "Ստանդարտ շեղում - ընդամենը ԱԱՀ կրեդիտ-ի հարաբերակցությունը ճշգրտված 20% բազային",
    "var7": "Ընդամենը ԱԱՀ կրեդիտ-ի հարաբերակցությունը ներմուծված և ձեռք բերված ապրանքների արժեքին",
    "var7_std": "Ստանդարտ շեղում - ընդամենը ԱԱՀ կրեդիտ-ի հարաբերակցությունը ներմուծված և ձեռք բերված ապրանքների արժեքին",
    "var8": "ԱԱՀ-ի դեբետային ճշգրտումների մասնաբաժինը ներմուծված և ձեռք բերված ապրանքների արժեքում",
    "var8_std": "Ստանդարտ շեղում - ԱԱՀ-ի դեբետային ճշգրտումների մասնաբաժինը ներմուծված և ձեռք բերված ապրանքների արժեքին",
    "var9": "Ճշգրտող հարկային հաշիվներով հարկման բազայի նվազեցման մասնաբաժինը ընդհանուր ԱԱՀ կրեդիտում",
    "var9_std": "Ստանդարտ շեղում - ճշգրտող հարկային հաշիվներով հարկման բազայի նվազեցման մասնաբաժինը ընդհանուր ԱԱՀ կրեդիտում",
    "var10": "Մատակարարի ճշգրտող հարկային հաշիվներով հարկման բազայի նվազեցման մասնաբաժինը ընդհանուր ԱԱՀ կրեդիտում",
    "var10_std": "Ստանդարտ շեղում - մատակարարի ճշգրտող հարկային հաշիվներով հարկման բազայի նվազեցման մասնաբաժինը ընդհանուր ԱԱՀ կրեդիտում",
    "n_MONTH_filed": "Հաշվետվություն ներկայացված ամիսների քանակը",
    "TOTAL": "Տարբեր ԱԱՀ դրույքաչափերի հարկման բազաների հանրագումարը",
    "TOTAL_CHANGE": "Տարբեր ԱԱՀ դրույքաչափերի հարկման բազաների հանրագումարի փոփոխությունը նախորդ տարվա համեմատ",
    "7a_CHANGE": "ԱԱՀ-ի 20% դրույքաչափով հարկման բազայի փոփոխությունը նախորդ տարվա համեմատ",
    "var1_CHANGE": "ԱԱՀ-ի 20% դրույքաչափով հարկման բազայի մասնաբաժնի փոփոխությունը նախորդ տարվա համեմատ",
    "var2_CHANGE": "ԱԱՀ-ի 16.67% դրույքաչափով հարկման բազայի մասնաբաժնի փոփոխությունը նախորդ տարվա համեմատ",
    "var3_CHANGE": "ԱԱՀ-ի 0% դրույքաչափով հարկման բազայի մասնաբաժնի փոփոխությունը նախորդ տարվա համեմատ",
    "var4_CHANGE": "ԱԱՀ-ի Հոդված 2 հարկման բազայի մասնաբաժնի փոփոխությունը նախորդ տարվա համեմատ",
    "var5_CHANGE": "ԱԱՀ-ի 0-ական դրույքաչափ/կրեդիտ մասնաբաժնի փոփոխությունը նախորդ տարվա համեմատ",
    "var6_CHANGE": "ԱԱՀ-ի կրեդիտ/ճշգրտված 20% բազայի մասնաբաժնի փոփոխությունը նախորդ տարվա համեմատ",
    "var7_CHANGE": "ԱԱՀ-ի կրեդիտ/ներմուծված և ձեռք բերված ապրանքների արժեքի մասնաբաժնի փոփոխությունը նախորդ տարվա համեմատ",
    "var8_CHANGE": "ԱԱՀ-ի դեբետային ճշգրտումներ/ ներմուծված և ձեռք բերված ապրանքների արժեքի մասնաբաժնի փոփոխությունը նախորդ տարվա համեմատ",
    "var9_CHANGE": "Ճշգրտող հարկային հաշիվներով հարկման բազայի նվազեցում/ընդհանուր ԱԱՀ կրեդիտի մասնաբաժնի փոփոխությունը նախորդ տարվա համեմատ",
    "AVG_N_EMPLOYEES": "Աշխատողների միջին քանակ",
    "EMPLOYEE_CHANGE": "Աշխատողների միջին քանակի փոփոխություն",
    "PERCENT_CHANGE": "Աշխատողների միջին քանակի տոկոսային փոփոխություն",
    "ROLLING_MEAN_EMP": "Նախորդ 4 ժամանակաշրջանների աշխատողների քանակի սահող միջին",
    "ROLLING_STD_EMP": "Նախորդ 4 ժամանակաշրջանների աշխատողների քանակի սահող ստանդարտ շեղում",
    "MOMENTUM": "Աշխատողների քանակի փոփոխության փոփոխությունը",
    "month_1": "Աշխատողների քանակը Հունվարին",
    "month_2": "Աշխատողների քանակը Փետրվարին",
    "month_3": "Աշխատողների քանակը Մարտին",
    "month_4": "Աշխատողների քանակը Ապրիլին",
    "month_5": "Աշխատողների քանակը Մայիսին",
    "month_6": "Աշխատողների քանակը Հունիսին",
    "month_7": "Աշխատողների քանակը Հուլիսին",
    "month_8": "Աշխատողների քանակը Օգոստոսին",
    "month_9": "Աշխատողների քանակը Սեպտեմբերին",
    "month_10": "Աշխատողների քանակը Հոկտեմբերին",
    "month_11": "Աշխատողների քանակը Նոյեմբերին",
    "month_12": "Աշխատողների քանակը Դեկտեմբերին",
    "Q1_Average": "Աշխատողների միջին քանակը առաջին եռամսյակում",
    "Q2_Average": "Աշխատողների միջին քանակը երկրորդ եռամսյակում",
    "Q3_Average": "Աշխատողների միջին քանակը երրորդ եռամսյակում",
    "Q4_Average": "Աշխատողների միջին քանակը չորրորդ եռամսյակում",
    "AVG_N_EMPLOYEES_2": "Աշխատողների միջին տարեկան քանակը",
    "MAX_N_EMPLOYEES_2": "Ամսական առավելագույն աշխատողների քանակը (տարվա մեջ)",
    "MIN_N_EMPLOYEES_2": "Ամսական նվազագույն աշխատողների քանակը (տարվա մեջ)",
    "Yearly_Average": "Աշխատողների միջին տարեկան քանակը",
    "Yearly_StdDev": "Աշխատողների տարեկան քանակի ստանդարտ շեղումը",
    "Yearly_Median": "Աշխատողների տարեկան քանակի մեդիանը",
    "Lag_Q1": "Աշխատողների միջին քանակը նախորդ տարվա առաջին եռամսյակում",
    "Lag_Q2": "Աշխատողների միջին քանակը նախորդ տարվա երկրորդ եռամսյակում",
    "Lag_Q3": "Աշխատողների միջին քանակը նախորդ տարվա երրորդ եռամսյակում",
    "Lag_Q4": "Աշխատողների միջին քանակը նախորդ տարվա չորրորդ եռամսյակում",
    "3-Month Rolling Average": "Նախորդ 3 ամսվա աշխատողների քանակի սահող միջին",
    "6-Month Rolling Average": "Նախորդ 6 ամսվա աշխատողների քանակի սահող միջին",
    "12-Month Rolling Average": "Նախորդ 12 ամսվա աշխատողների քանակի սահող միջին",
    "MAX_EMPLOYEE_CHANGE_2": "Ամսական առավելագույն աշխատողների քանակի (տարվա մեջ) փոփոխությունը նախորդ տարվա համեմատ",
    "EMPLOYEE_CHANGE_2": "Աշխատողների միջին տարեկան քանակի փոփոխությունը նախորդ տարվա համեմատ",
    "PERCENT_CHANGE_2": "Աշխատողների միջին տարեկան քանակի տոկոսային փոփոխությունը նախորդ տարվա համեմատ",
    "MOMENTUM_2": "Աշխատողների քանակի փոփոխության փոփոխության փոփոխությունը նախորդ տարվա համեմատ",
    "supplier_COUNT_mean": "Մատակարարի հետ միջին գործարքների քանակը",
    "supplier_COUNT_std": "Մատակարարի հետ գործարքների քանակի ստանդարտ շեղումը",
    "supplier_TOTAL_PRICE_SUM_mean": "Մատակարարի հետ գործարքների միջին ընդհանուր արժեքը",
    "supplier_TOTAL_PRICE_SUM_std": "Մատակարարի հետ գործարքների ընդհանուր արժեքի ստանդարտ շեղումը",
    "supplier_TOTAL_VAT_SUM_mean": "Մատակարարի հետ գործարքների ընդհանուր ԱԱՀ-ի միջին արժեքը",
    "supplier_TOTAL_VAT_SUM_std": "Մատակարարի հետ գործարքների ընդհանուր ԱԱՀ-ի արժեքի ստանդարտ շեղումը",
    "supplier_TOTAL_VAT_MAX_max": "Առավելագույն ԱԱՀ-ն ըստ մատակարարի",
    "supplier_TOTAL_VAT_MAX_std": "Առավելագույն ԱԱՀ-ն ըստ մատակարարի ստանդարտ շեղումը",
    "supplier_TOTAL_VAT_MIN_min": "Նվազագույն ԱԱՀ-ն ըստ մատակարարի",
    "supplier_TOTAL_VAT_MIN_std": "Նվազագույն ԱԱՀ-ն ըստ մատակարարի ստանդարտ շեղումը",
    "buyer_COUNT_mean": "Գնորդի հետ միջին գործարքների քանակը",
    "buyer_COUNT_std": "Գնորդի հետ գործարքների քանակի ստանդարտ շեղումը",
    "buyer_TOTAL_PRICE_SUM_mean": "Գնորդի հետ գործարքների միջին ընդհանուր արժեքը",
    "buyer_TOTAL_PRICE_SUM_std": "Գնորդի հետ գործարքների ընդհանուր արժեքի ստանդարտ շեղումը",
    "buyer_TOTAL_VAT_SUM_mean": "Գնորդի հետ գործարքների ընդհանուր ԱԱՀ-ի միջին արժեքը",
    "buyer_TOTAL_VAT_SUM_std": "Գնորդի հետ գործարքների ընդհանուր ԱԱՀ-ի արժեքի ստանդարտ շեղումը",
    "buyer_TOTAL_VAT_MAX_max": "Առավելագույն ԱԱՀ-ն ըստ գնորդի",
    "buyer_TOTAL_VAT_MAX_std": "Ստանդարտ շեղում - առավելագույն ԱԱՀ-ն ըստ գնորդի",
    "buyer_TOTAL_VAT_MIN_min": "Նվազագույն ԱԱՀ-ն ըստ գնորդի",
    "buyer_TOTAL_VAT_MIN_std": "ստանդարտ շեղում - նվազագույն ԱԱՀ-ն ըստ գնորդի",
    "still_in_business": "Ընկերությունը գործում է",
    "Years_in_business": "Գործող տարիների քանակը",
    "level1_A41": "Ոլորտի միջին համախառն եկամուտը (A41)",
    "level1_A85": "Ոլորտի միջին հարկվող շահույթը/հարկային վնասը (A85)",
    "level1_A84": "Ոլորտի միջին ընդամենը նվազեցումները (A84)",
    "level1_A50": "Ոլորտի միջին վարչական ծախսերը (A50)",
    "level1_7a": "Ոլորտի միջին ԱԱՀ-ի 20% դրույքաչափով հարկվող գործարքների հարկային բազան (7a)",
    "level1_var1": "Ոլորտի միջին ԱԱՀ-ի 20% դրույքաչափով հարկման բազայի մասնաբաժինը ընդհանուր ԱԱՀ-ով վաճառքներում",
    "level1_var2": "Ոլորտի միջին ԱԱՀ-ի 16.67% դրույքաչափով մասնաբաժինը ընդհանուր ԱԱՀ-ով վաճառքներում",
    "level1_var3": "Ոլորտի միջին ԱԱՀ-ի 0% դրույքաչափով հարկման բազայի մասնաբաժինը ընդհանուր ԱԱՀ-ով վաճառքներում",
    "level1_var4": "Ոլորտի միջին ԱԱՀ-ի Հոդված 2 հարկման բազայի մասնաբաժինը ընդհանուր ԱԱՀ-ով վաճառքներում",
    "level1_var5": "Ոլորտի միջին ԱԱՀ-ի 0-ական դրույքաչափով հարկվող և ԱԱՀ-ից ազատված գործարքների (Հոդված 2) հարաբերակցությունը ընդամենը ԱԱՀ-ի կրեդիտին",
    "level1_var6": "Ոլորտի միջին ընդամենը ԱԱՀ կրեդիտ-ի հարաբերակցությունը ճշգրտված 20% բազայի հետ",
    "level1_var7": "Ոլորտի միջին ընդամենը ԱԱՀ կրեդիտ-ի հարաբերակցությունը ներմուծված և ձեռք բերված ապրանքների արժեքին",
    "level1_var8": "Ոլորտի միջին ԱԱՀ-ի դեբետային ճշգրտումների մասնաբաժինը ներմուծված և ձեռք բերված ապրանքների արժեքում",
    "level1_var9": "Ոլորտի միջին ճշգրտող հարկային հաշիվներով հարկման բազայի նվազեցման մասնաբաժինը ընդհանուր ԱԱՀ կրեդիտում",
    "level1_AVG_N_EMPLOYEES": "Ոլորտի միջին աշխատողների քանակը",
    "level1_AUDIT_ANY": "Ոլորտի միջին ստուգումների քանակը",
    "level1_FRAUD_ANY": "Ոլորտի միջին խարդախության դեպքերի քանակը",
    "sector_share": "Ոլորտի մասնաբաժին",
    "sector_comparison": "Ոլորտի համեմատություն",
    "productivity": "Արդյունավետություն",
    "profitability": "Շահութաբերություն",
    "import_ratio": "Ներմուծման մասնաբաժին",
}
